# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Aday' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Aday

  target 'Aday-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
	
  pod 'Firebase/Messaging'
  pod 'Firebase/Core', '4.9.0'
  pod 'Firebase/Messaging', '4.9.0'
  pod 'FirebaseAnalytics', '4.0.9'

  target 'AdayTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Aday-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Aday-tvOS

end
