/* @flow */

import React from 'react';
import {
    StyleSheet,
    View,
    Text,
    ScrollView,
    Image
} from 'react-native';
import HTMLView from 'react-native-htmlview';

function renderNode(node, index) {
    if (node.name == 'iframe') {
        return (
            <View key={index} style={{width: 200, height: 200}}>
                <Text>
                    {node.attribs.src}
                </Text>
      </View>
        );
    }
}
const htmlContent = `
    <p>TERMS OF SERVICE</p>
<p>Aday Technologies, Inc.</p>
<p><strong><em>Effective Date: April 22, 2017</em></strong></p>
<p>&nbsp;</p>
<p>Welcome to the website and online service platform of Aday Technologies, Inc. (&ldquo;Aday Technologies&rdquo;, &ldquo;Aday&rdquo;, the &ldquo;Company&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo; or &ldquo;our&rdquo;). This page explains the Terms of Service (&ldquo;Terms&rdquo;) which govern your use of our websites (individually and collectively, the &ldquo;Site&rdquo;) and related products and services, including mobile applications, developer platforms, premium services, plug-ins or any content or information provided as part of the Site (the &ldquo;Services&rdquo;), and are an agreement between you and Aday. These Terms do not apply to third party websites, applications, or content (including advertising).</p>
<p>These Terms may apply to you individually (&ldquo;Personal User&rdquo;), the business or other legal entity user you represent (&ldquo;Business User&rdquo;), or both. If you are using the Site or Services on behalf of a company or other legal entity (i.e. a Business User), you hereby represent and warrant that you have the authority to enter into these Terms on behalf of the Business User. Notwithstanding the foregoing, these Terms shall not apply to any Business User that has an existing agreement with us to the extent such other agreement governs such Business User&rsquo;s use of the applicable Services. However, if a Business User has a separate agreement with us for certain Services, but not other Services, these Terms shall govern such other Services that are not already governed by an agreement with Aday. Additionally, if you are a natural person using the Site or Services on behalf of a company or other legal entity, you, as a Personal User, are nevertheless individually bound by these Terms even if your company has a separate agreement with us. As used in these Terms and unless separately identified as applicable to either a Personal User or Business User only, &ldquo;you&rdquo; and &ldquo;your&rdquo; refer to both you individually (Personal User) and, to the extent these Terms apply, the company on behalf of which you are entering into these Terms (Business User).</p>
<p>1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Acceptance of Terms and Conditions</p>
<p>By accessing the Site or using the Services, you: (1) acknowledge that you have read and understand these Terms; (2) agree to be bound by them in their entirety, and (3) are entering into a legally binding agreement with us. These Terms apply no matter what computer or device you use to access the Services.</p>
<p>Our Privacy Policy, is incorporated by reference into these Terms. Please read these Terms and the Privacy Policy before you access the Site or Services, as these Terms form a binding legal agreement between you and Aday Technologies.</p>
<p>From time-to-time it will be necessary for us to make updates to these Terms. We may add to, change or remove any part of these Terms, at any time without prior notice to you other than listing of a later effective date than the one set forth at the top of these Terms. It is your responsibility to check these Terms periodically for changes. Such modification shall be effective immediately upon posting at the Site. Your continued use of our Site and / or Services following the posting of changes to these Terms will mean that you accept those changes.</p>
<p>IF YOU DO NOT AGREE TO ALL OF THESE TERMS, DO NOT USE THE SITE OR SERVICES. YOUR USE OF OUR SITE AND SERVICES REQUIRES YOUR ACCEPTANCE OF THESE TERMS AS THEY MAY BE AMENDED FROM TIME TO TIME, INCLUDING THE POLICIES INCORPORATED BY REFERENCE HEREIN, WHICH INCLUDES THE ADAY&rsquo;S PRIVACY POLICY.</p>
<p>THESE TERMS CONTAINS A MANDATORY INDIVIDUAL ARBITRATION PROVISION WITH A CLASS ACTION AND JURY TRIAL WAIVER THAT REQUIRES THE USE OF ARBITRATION ON AN INDIVIDUAL BASIS TO RESOLVE ANY DISPUTES ARISING OUT OF OR RELATING TO THESE TERMS, RATHER THAN JURY TRIALS OR CLASS ACTION LAWSUITS.</p>
<p>2.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Notices and Disclosures</p>
<p>You acknowledge and agree that Aday may provide notices and other disclosures to you, required by these Terms, any other agreement, or law, electronically by posting such notices or other disclosures on Aday&rsquo;s Site or by emailing it to you at any email address provided to Aday by you. By providing Aday with your email address and/or mobile number, at any time during your use of our Site or Services, you consent to our using the email address and/or mobile number to send you Service-related notices, including any required by law, in lieu of communication by postal mail, as well as other messages, such as changes to features of the Service and special offers. Such notices or other disclosures shall be considered received by you following the posting on the website or twenty-four (24) hours following the email being sent to you, as applicable. Any such electronic notice or other disclosure shall have the same effect and meaning as if it had been provided to you as a paper copy.</p>
<p>3.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Use of our Services</p>
<p>A.&nbsp;&nbsp;&nbsp;&nbsp;Authorized User</p>
<p>You may not access or use the Site or Services if you are unable to form a binding, legal agreement with Aday. You affirm that you have the authority to enter into these Terms. You assume all responsibility for your use of, and access to, the Site or Services.</p>
<p>The Service is designed for use by employers and employees in the United States. You are not authorized to use the other features of the Service for employees not located in the United States, unless prior written approval is obtained from Aday Technologies.</p>
<p>Accounts are for a single user, company or other legal entity, as applicable. Any multiple-party use, other than individual use on behalf of Business User, is prohibited. For example, sharing a login between Personal Users and other individuals is prohibited.</p>
<p>B.&nbsp;&nbsp;&nbsp;&nbsp;Account Types and Use</p>
<p>Your Aday account gives you access to the services and functionality that we may establish and maintain from time to time and in our sole discretion. We may maintain different types of accounts for different types of Users. If you open an Aday account on behalf of a company, organization, or other entity, then (a) &ldquo;you&rdquo; includes you and that entity, and (b) you represent and warrant that you are an authorized representative of the entity with the authority to bind the entity to these Terms, and that you agree to these Terms on the entity&rsquo;s behalf. By connecting to Aday with a third-party service, you give us permission to access and use your information from that service as permitted by that service, and to store your log-in credentials for that service. You may never use another User&rsquo;s account without permission.</p>
<p>C.&nbsp;&nbsp;&nbsp;&nbsp;Eligibility</p>
<p>To be eligible to use the Site or Services, you represent and warrant that you: (i) are not currently restricted from the Site or Services and are not otherwise prohibited from having an account related thereto; (ii) will only maintain one account at any given time; (iii) will only provide accurate information to Aday; (iv) have full power and authority to enter into these Terms and doing so will not violate any other agreement to which you are a party; and (v) will not violate any rights of Aday or a third party, including intellectual property rights.</p>
<p>D.&nbsp;&nbsp;&nbsp;License for Use of our Site and Service</p>
<p>Subject to these Terms, you are hereby granted a non-exclusive, limited, non-transferable, non-sub-licensable, freely revocable license to use the Site and Services, solely as permitted by the features of the Services, which may vary by User. This license is personal to you, and you may not resell our Services, permit other users access to our Services through your account, or use the Services to host content for others. You may not copy or download any content from the Site or Services except with the prior approval of Aday, as may be obtained in writing or through your use of features built into the Site or Services by Aday (for example, the Service may provide the user the ability to download some information from the website, such as number of hours or schedules). You acknowledge that, except as otherwise expressly provided, these Terms are solely between you and Aday.</p>
<p>Furthermore, without the prior written approval of Aday, you may not distribute, publicly perform or display, lease, sell, transmit, transfer, publish, edit, copy, create derivative works from, rent, sub-license, distribute, decompile, disassemble, reverse engineer or otherwise make unauthorized use of Site content or Services. You agree not to remove, obscure, or alter copyright, patent, trademark, or other proprietary rights notices affixed to the Site or Services. Your rights are subject to your compliance with these Terms as well as any other agreements applicable to the Services you are using.</p>
<p>We reserve all rights not expressly granted herein in the Service and the proprietary rights and property of Aday, as defined in&nbsp;<a href="#_Proprietary_Rights_and">Section 9</a>&nbsp;below. Aday reserves the right to limit your use of or access to the Site or Services, in its sole discretion in order to maintain the performance and availability of the Site and to enforce these Terms of Service. Such limitations include, though are not limited to, Aday&rsquo;s ability to terminate this license or your access to the Service, at any time for any reason or no reason.</p>
<p>4.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Acceptable Use</p>
<p>The purpose of the Aday Services is to enable functionality among Business Users and Personal Users, including scheduling and performance management. As a technology platform, Aday is not a participant in the communication between Users.</p>
<p>A.&nbsp;&nbsp;&nbsp;&nbsp;Interactions with Other Users</p>
<p>You are solely responsible for your interactions with other Aday Users. You acknowledge and agree they are responsible for making your own decisions regarding persons you employee or job positions you take, as applicable. You acknowledge and agree that we do not conduct user background checks or verify any content or other information provided by users on the Site or Services. Aday offers various forums which allow you to post comments. Aday also enables sharing of information by allowing users to post content and information, including links and information regarding certain job opportunities. Pursuant to the license granted by you above, Aday may grant other users of the Site or Services access and share rights to your content in accordance with these Terms, your settings and the nature of your connection with such other users. Information you share may be seen and used by other users of the Site or Services. Aday cannot guarantee that users of the Site or Services will not use the information that you share on Aday, nor the manner of use. Aday is not responsible for another user&rsquo;s or other third party&rsquo;s misappropriation or misuse of your content or other information. You are solely responsible for your interactions with other users. Additionally, Aday is not responsible for the truthfulness, accuracy, authenticity, or completeness of any of the content or any other information provided by other users or any other third party. You hereby release Aday from all claims, demands, or damages of every kind, known or unknown, in any way connected with (i) any relationship arising between users of the Site or Service, (ii) any dispute between you and another user, or (iii) arising out of any services which originated through the Site or Services or were otherwise provided by a user. Additionally, you agree to immediately report to us any false information provided or misconduct by any user of the Site or Services.</p>
<p>Aday makes it easy for you to add other Users to your Aday account, and to invite new Users to join Aday&rsquo;s Services. YOU REPRESENT AND WARRANT TO US THAT EACH PERSON YOU ADD TO YOUR ADAY ACCOUNT HAS CONSENTED TO BE ADDED TO THE ACCOUNT AND TO RECEIVE ADMINISTRATIVE MESSAGES FROM ADAY AND TEXT MESSAGES FROM YOU AND ANYONE ELSE ASSOCIATED WITH THE ACCOUNT.</p>
<p>B.&nbsp;&nbsp;&nbsp;&nbsp;No Working Relationship</p>
<p>Aday&rsquo;s Services provide a platform for Business Users, Personal Users and third-parties to connect and share employment and other opportunities. Nothing described herein, nor any of Aday&rsquo;s Services, shall create an employment, contracting, or other working relationship (&ldquo;Working Relationship&rdquo;) between you and Aday. You shall be solely responsible for any User Content or other content that you share with Users or third-parties, whether directly through, or as a result of, the use of our Services. You shall also be solely responsible for ensuring that any Working Relationship that results between you and other Users as a result of your use of our Services, is compliant with local laws, policies, and regulations.</p>
<p>Further, Aday takes no responsibility for any liabilities, claims, damages, or loss that may result from a Working Relationship that developed between you and another User.</p>
<p>C.&nbsp;&nbsp;&nbsp;&nbsp;No Co-Employment or Poaching</p>
<p>Aday&rsquo;s Services shall not be used to promote, support, or create a relationship between any persons, Users or otherwise, whereby two or more employers have actual or potential legal rights and duties with respect to the same employee (&ldquo;Co-Employment&rdquo;). Further, Aday&rsquo;s Site and Services are in no way to be used to solicit employees employed by other Users of Aday, unless expressly permitted by a separate written agreement between you and Aday, or you and the other employer. In accordance with&nbsp;<a href="#_No_Working_Relationship">Subsection 4.B</a>, Aday assumes no responsibility for any Working Relationships resulting from your use of our Services, and any use of our Services in furtherance of Working Relationships in contravention of these Terms may result may cause Aday to remove or delete your Content, account, or profile from the Site or Services, at any time in its sole discretion.</p>
<p>D.&nbsp;&nbsp;&nbsp;Service Rules and Restrictions</p>
<p>You agree not to engage in any of the following prohibited activities: (i) copying, distributing, or disclosing any part of the Service in any medium, including without limitation by any automated or non-automated &ldquo;scraping&rdquo;; (ii) using any automated system, including without limitation &ldquo;robots,&rdquo; &ldquo;spiders,&rdquo; &ldquo;offline readers,&rdquo; etc., to access the Service in a manner that sends more request messages to the Aday servers than a human can reasonably produce in the same period of time by using a conventional on-line web browser (except where Aday provides functionality as a part of the Service to import certifications, human resources, people management, and payroll information, as well as social media information, to enhance your account.); (iii) uploading, posting, hosting, or transmitting spam, chain letters, SMSs or other unsolicited email or messages; (iv) attempting to interfere with, compromise the system integrity or security or decipher any transmissions to or from the servers running the Service; (v) taking any action that imposes, or may impose at our sole discretion an unreasonable or disproportionately large load on our infrastructure; (vi) uploading invalid data, viruses, worms, or other software agents or any code of a destructive nature through the Service; (vii) collecting or harvesting any personally identifiable information, including account names, from the Service; (viii) using the Service for any commercial solicitation purposes; (ix) impersonating another person or otherwise misrepresenting your affiliation with a person or entity, conducting fraud, hiding or attempting to hide your identity; (x) interfering with the proper working of the Service; (xi) accessing any content on the Service through any technology or means other than those provided or authorized by the Service; (xii) bypassing the measures we may use to prevent or restrict access to the Service, including without limitation features that prevent or restrict use or copying of any content or enforce limitations on use of the Service or the content therein; (xiii) verbally, physically or other abuse (including threats of abuse or retribution) of any other User or any Aday customer, employee, member, or officer; (xiv) reproducing, duplicating, copying, selling, reselling or otherwise exploiting any portion of the Service, use of the Service, or access to the Service without the express written permission by Aday; or (xv) modifying, adapting or hacking the Service or modifying another website so as to falsely imply that it is associated with the Service, Aday, or any other Aday service. Aday&rsquo;s Services are not intended to be used in countries where offering or providing the Services is illegal, and we do not offer the Services in such countries or to citizens of such countries.</p>
<p>BY USING THE SERVICE YOU REPRESENT AND WARRANT UNDER PENALTY OF PERJURY THAT (I) YOU DO NOT WORK FOR A COMPETITOR OF THE COMPANY; AND (II) THAT YOU WILL NOT PROVIDE ANY INFORMATION GAINED FROM YOUR USE OF OR ACCESS TO THE SITE OR THE SERVICES TO A COMPETITOR OF THE COMPANY.</p>
<p>We may, without prior notice, change the Service; stop providing the Service or features of the Service, to you or to Users generally; or create usage limits for the Service. We may permanently or temporarily terminate or suspend your access to the Service without notice and liability for any reason, including if in our sole determination you violate any provision of these Terms, or for any or no reason. Upon termination for any reason or no reason, you continue to be bound by these Terms.</p>
<p>You are solely responsible for your interactions with other Aday Users. We reserve the right, but have no obligation, to monitor disputes between you and other Users. We shall have no liability for your interactions with other Users, or for any User&rsquo;s action or inaction.</p>
<p>5.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;User Content</p>
<p>A.&nbsp;&nbsp;&nbsp;&nbsp;User Content Defined; Representation and Warranty of Content</p>
<p>Some areas of the Service allow Users to post or provide content such as profile information, images, comments, questions, and other content or information. Any such materials a User submits, posts, displays, or otherwise makes available on the Service is referred to as &ldquo;User Content&rdquo; (or &ldquo;Content&rdquo;). For Business Users, this Content also includes any information provided about your employees, including contact and application information, background check information, drug testing results, payroll status and details, and pay structure. For Personal Users, this Content also includes any information provided about you by your employer, including contact and application information, background check information, drug testing results, payroll status and details, and pay structure. We claim no ownership rights over User Content created by you and the User Content you create remains yours. However, by providing or sharing User Content through the Service, you agree to allow others to view, edit, and/or share your User Content in accordance with your settings and these Terms. Any Content you submit to us is provided at your own risk of loss. You are solely responsible for all Content you share or permit to be shared (by your employee or employer), provide, display, publish, or disseminate to others, whether such action was taken by us or you. Aday may (but shall not be required to) also remove or delete your Content from the Site or Services at any time in its sole discretion. The User Content may be viewed or shared with others in accordance with your profile settings and the Privacy Policy.</p>
<p>In connection with your User Content, you affirm, represent and warrant the following:</p>
<ol>
<li>You have the written consent of each and every identifiable natural person in the User Content, if any, to use such person&rsquo;s name or likeness in the manner contemplated by the Service and these Terms, and each such person has released you from any liability that may arise in relation to such use.</li>
<li>If applicable, you have the consent and appropriate rights in the User Content to use your employer&rsquo;s logos, trademarks, trade names or service marks in the manner contemplated by the Service or these Terms.</li>
<li>You have obtained and are solely responsible for obtaining all consents as may be required by law to post any User Content relating to third parties.</li>
<li>Your User Content and Aday&rsquo;s use thereof as contemplated by these Terms and the Service will not violate any law or infringe any rights of any third party, including but not limited to any Intellectual Property Rights and privacy rights.</li>
<li>Aday may exercise the rights to your User Content granted under these Terms without liability for payment of any guild fees, residuals, payments, fees, or royalties payable under any collective bargaining agreement or otherwise.</li>
<li>To the best of your knowledge, all User Content and other information that you provide to us is truthful and accurate.</li>
</ol>
<p>By posting or otherwise making available any User Content on or through the Service, you expressly grant, and you represent and warrant that you have all rights necessary to grant, to Aday a royalty-free, sub-licensable, transferable, perpetual, irrevocable, non-exclusive, worldwide license to use, reproduce, modify, publish, list information regarding, edit, translate, distribute, syndicate, publicly perform, publicly display, and make derivative works of all such User Content and your name, voice, and/or likeness as contained in your User Content, in whole or in part, and in any form, media or technology, whether now known or hereafter developed, for use in connection with the Service and Aday&rsquo;s (and its successors&rsquo; and affiliates&rsquo;) business, including without limitation for promoting and redistributing part or all of the Service (and derivative works thereof) in any media formats and through any media channels.</p>
<p>B.&nbsp;&nbsp;&nbsp;&nbsp;Ownership of Content</p>
<p>As between you and Aday, you own the information, materials, photos, or other Content you provide Aday under these Terms. Any Content that you upload or otherwise provide to Aday in connection with the Site or Services may be used by Aday in order to provide and promote the Site, Services or Aday&rsquo;s business, subject to the Aday&rsquo;s Privacy Policy. Except as otherwise provided herein or as otherwise provided in any other agreement between you and Aday, you retain all rights to the Content.</p>
<p>C.&nbsp;&nbsp;&nbsp;&nbsp;Business User License</p>
<p>As a Business User, you grant to Aday, and all of its subsidiaries, affiliates, successors, and assigns a worldwide perpetual, royalty-free, fully paid, sub-licensable, non-exclusive, and transferable right to use, publish, reproduce, distribute, modify, adapt, publicly display and otherwise use the Content as reasonably necessary and appropriate to provide the Services. Additionally, you authorize us to use your corporate logo and corporate name, if applicable, for any promotional purposes; to opt-out of this specific authorization, contact us via email or by using the Contact Us page available through the Site and Services.</p>
<p>D.&nbsp;&nbsp;&nbsp;Personal User License</p>
<p>As a Personal User, you grant to Aday, and all of its subsidiaries, affiliates, successors, and assigns, a worldwide, perpetual, royalty-free, fully paid, sub-licensable, non-exclusive, and transferable right to use, publish, reproduce, distribute, modify, prepare derivative works of, adapt, publicly display and otherwise use the Content. Such right to use such Content shall survive the termination of these Terms and termination of the Services. You authorize us to use, forward, or post your profile or related information on other sites and services.</p>
<p>E.&nbsp;&nbsp;&nbsp;&nbsp;No Liability</p>
<p>Aday takes no responsibility and assumes no liability for any User Content that you or any other User or third party posts, sends, or otherwise makes available over the Service. You shall be solely responsible for your User Content and the consequences of posting, publishing it, sharing it, or otherwise making it available on the Service, and you agree that we are only acting as a passive conduit for your online distribution and publication of your User Content. You understand and agree that you may be exposed to User Content that is inaccurate, objectionable, inappropriate for children, or otherwise unsuited to your purpose, and you agree that Aday shall not be liable for any damages you allege to incur as a result of or relating to any User Content.</p>
<p>Further, you agree that your use of the Site and Services are at your sole risk, and you will not hold Aday, or its third-party service providers, licensors and suppliers, as applicable, responsible for any loss or damage that results from your access to or use of the Services, including without any limitation any loss or damage resulting from the loss of any and all of the data related to your account. You agree and understand that it is your responsibility to backup your data and to ensure such backups are secure.</p>
<p>F.&nbsp;&nbsp;&nbsp;&nbsp;Accuracy</p>
<p>By registering for our Services, you represent and warrant that all information you submit to us is true, accurate, current and complete and that you will promptly notify us in writing if your information changes. It is your responsibility to keep your account and profile information accurate and updated. We are not responsible for any disputes or claims related to any inaccurate, incomplete, or untimely information provided by you to us.</p>
<p>G.&nbsp;&nbsp;&nbsp;Collection of Personal Content and Privacy</p>
<p>You may browse the Site without providing us with any personal information; however, to use our Services, you must register with us and submit certain personally identifiable information. You expressly agree that we may collect, disclose, store and otherwise use your information in accordance with Aday&rsquo;s Privacy Policy.</p>
<p>H.&nbsp;&nbsp;&nbsp;Importing of Human Resource Information Permitted</p>
<p>The Services may allow you (if you are a Business User) or your employer (if you are a Personal User) to import information from human resource and other employee and payroll management software, such as, but not limited to, wheniwork.com and PeopleSoft. By directly integrating these services, we attempt to make your account richer and more personalized. Any Content obtained in this manner will be used, stored, and disclosed in accordance with our Privacy Policy. However, please remember that the manner in which these software providers use, store and disclose your information is governed by the policies of such third parties, and Aday shall have no liability or responsibility for the privacy practices or other actions of such parties.</p>
<p>I.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Social Media Interaction</p>
<p>The Services may allow you to enable or log in to the Services via various social networking services like Facebook, Twitter, or LinkedIn (&ldquo;Social Network Service(s)&rdquo;). By directly integrating these services, we attempt to make your online experiences richer and more personalized. To take advantage of this feature, we will ask you to log into or grant us permission via the relevant Social Network Service. When you add a Social Network Services account to the Service or log into the Service using your Social Network Services account, we will collect relevant information necessary to enable the Service to access that Social Network Service and your data contained within that Social Network Service. As part of such integration, the Social Network Service will provide us with access to certain information that you have provided to the Social Network Service, and we will use, store and disclose such information in accordance with our Privacy Policy. However, please remember that the manner in which Social Network Services use, store and disclose your information is governed by the policies of such third parties, and Aday shall have no liability or responsibility for the privacy practices or other actions of any Social Network Services that may be enabled within the Service.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
<p>J.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Appropriate Content</p>
<p>You agree not to post User Content that: (i) may create a risk of harm, loss, physical or mental injury, emotional distress, death, disability, disfigurement, or physical or mental illness to you, to any other person, or to any animal; (ii) may create a risk of any other loss or damage to any person or property; (iii) seeks to harm or exploit children by exposing them to inappropriate content, asking for personally identifiable details or otherwise; (iv) may constitute or contribute to a crime or tort; (v) contains any information or content that we deem to be unlawful, harmful, abusive, racially or ethnically offensive, defamatory, infringing, invasive of personal privacy or publicity rights, harassing, humiliating to other people (publicly or otherwise), libelous, threatening, profane, obscene, or otherwise objectionable; (vi) contains any information or content that is illegal (including, without limitation, the disclosure of insider information under securities law or of another party&rsquo;s trade secrets); (vii) contains any information or content that you do not have a right to make available under any law or under contractual or fiduciary relationships; (viii) contains any information or content that you know is not correct and current or (ix) violates any company, employer or other applicable policy.</p>
<p>K.&nbsp;&nbsp;&nbsp;&nbsp;No Third-Party Rights Violation</p>
<p>You agree that any User Content that you post does not and will not violate third-party rights of any kind, including without limitation any Intellectual Property Rights (as defined below), rights of privacy or other rights of Aday or any third party. For the purposes of these Terms, &ldquo;Intellectual Property Rights&rdquo; means all patent rights, copyright rights, mask work rights, moral rights, rights of publicity, trademark, trade dress and service mark rights, goodwill, trade secret rights and other intellectual property rights as may now exist or hereafter come into existence, and all applications therefore and registrations, renewals and extensions thereof, under the laws of any state, country, territory or other jurisdiction.</p>
<p>Aday reserves the right, but is not obligated, to reject and/or remove any User Content that Aday believes, in its sole discretion, violates any of these provisions or is otherwise unlawful, offensive, threatening, libelous, defamatory, pornographic, obscene or otherwise objectionable. You understand that publishing your User Content on the Service is not a substitute for registering it with the U.S. Copyright Office, or any other rights organization.</p>
<p>6.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Mobile Applications or Site</p>
<p>A.&nbsp;&nbsp;&nbsp;&nbsp;Mobile Software</p>
<p>We may make available software to access the Services via a mobile device (&ldquo;Mobile Software&rdquo;). To use the Mobile Software you must have a mobile device that is compatible with the Mobile Software. Aday does not warrant that the Mobile Software will be compatible with your mobile device. You may use mobile data in connection with the Mobile Software and may incur additional charges from your mobile service provider for the access to or use of the Mobile Software. You agree that you are solely responsible for any such charges. Aday hereby grants you a non-exclusive, non-transferable, revocable license to use a compiled code copy of the Mobile Software for your Aday account on your mobile device or devices, owned or leased by you, for your personal use, except where you are a Business User and your mobile device or devices are owed or leased by your employer for your use in your capacity as an employee. You may not: (i) modify, disassemble, decompile or reverse engineer the Mobile Software, except to the extent that such use is expressly allowed by law; (ii) rent, lease, loan, resell, sublicense, distribute, or otherwise transfer the Mobile Software to any third party or use the Mobile Software to provide time sharing or similar services for any third party; (iii) make any copies of any kind of the Mobile Software; (iv) remove, circumvent, disable, damage, or otherwise interfere with the security or security-related features of the Mobile Software, features that prevent or restrict use or copying of any content accessible through the Mobile Software, or features that enforce limitations on use of the Mobile Software; or (v) delete the copyright and other proprietary rights notices on the Mobile Software. You acknowledge that Aday may from time to time issue upgraded versions of the Mobile Software and may automatically electronically update the version of the Mobile Software that you are using on your mobile device. You consent to such automatic updating on your mobile device and agree that the terms and conditions of these Terms will apply to all such updates. Any third-party code that may be incorporated in the Mobile Software is covered by the applicable open source or third-party end user license agreement, if any, authorizing use of such code. The foregoing license grant is not a sale of the Mobile Software or any copy thereof, and Aday or its third-party partners or suppliers retain all right, title, and interest in the Mobile Software (and any copy thereof). Any attempt by you to transfer any of the rights, duties, or obligations hereunder, except as expressly provided for in these Terms, is void. Aday reserves all rights not expressly granted under these Terms. Aday may also send you Push Notifications if you authorize Aday to do so.</p>
<p>B.&nbsp;&nbsp;&nbsp;&nbsp;Mobile Software provided from the App Store by Apple</p>
<p>The following applies to any Mobile Software you acquire from the Apple App Store (&ldquo;App Store-Sourced Software&rdquo;): You acknowledge and agree that these Terms is solely between you and Aday, not Apple, and that Apple has no responsibility for the App Store-Sourced Software or content thereof. Your use of the App Store-Sourced Software must comply with the App Store Terms of Service. You acknowledge that Apple has no obligation whatsoever to furnish any maintenance and support services with respect to the App Store-Sourced Software. In the event of any failure of the App Store-Sourced Software to conform to any applicable warranty, you may notify Apple, and Apple will refund the purchase price for the App Store-Sourced Software to you; to the maximum extent permitted by applicable law, Apple will have no other warranty obligation whatsoever with respect to the App Store-Sourced Software, and any other claims, losses, liabilities, damages, costs or expenses attributable to any failure to conform to any warranty will be solely governed by these Terms and any law applicable to Aday as provider of the software. You acknowledge that Apple is not responsible for addressing any claims of you or any third party relating to the App Store-Sourced Software or your possession and/or use of the App Store-Sourced Software, including, but not limited to: (i) product liability claims; (ii) any claim that the App Store-Sourced Software fails to conform to any applicable legal or regulatory requirement; and (iii) claims arising under consumer protection or similar legislation; and all such claims are governed solely by these Terms and any law applicable to Aday as provider of the software. You acknowledge that, in the event of any third-party claim that the App Store-Sourced Software or your possession and use of that App Store-Sourced Software infringes that third party&rsquo;s intellectual property rights, Aday, not Apple, will be solely responsible for the investigation, defense, settlement and discharge of any such intellectual property infringement claim to the extent required by these Terms. You and Aday acknowledge and agree that Apple, and Apple&rsquo;s subsidiaries, are third-party beneficiaries of these Terms as relates to your license of the App Store-Sourced Software, and that, upon your acceptance of the terms and conditions of these Terms, Apple will have the right (and will be deemed to have accepted the right) to enforce these Terms as relates to your license of the App Store-Sourced Software against you as a third-party beneficiary thereof.</p>
<p>C.&nbsp;&nbsp;&nbsp;&nbsp;Mobile Software provided from the Google Play Store</p>
<p>The following applies to any Mobile Software you acquire from the Google Play Store (&ldquo;Google-Sourced Software&rdquo;): (i) you acknowledge that these Terms are between you and Aday only, and not with Google, Inc. (&ldquo;Google&rdquo;); (ii) your use of Google-Sourced Software must comply with Google&rsquo;s then-current Google Play Store Terms of Service; (iii) Google is only a provider of the Google Play Store where you obtained the Google-Sourced Software; (iv) Aday, and not Google, is solely responsible for its Google-Sourced Software; (v) Google has no obligation or liability to you with respect to Google-Sourced Software or the Terms; and (vi) you acknowledge and agree that Google is a third-party beneficiary to the Terms as it relates to Aday&rsquo;s Google-Sourced Software.</p>
<p>7.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Text Messaging</p>
<p>You may sign up to receive certain Company notifications or information via text messaging. As part of the Services, you may sometimes receive administrative messages from Aday. By signing up for Aday, you agree to receive text messages from us, unless and until you use turn off text messages using the Settings &gt; Communication &gt; Preferences page available through the Service. You may incur additional charges from your mobile service provider for these services. You agree that you are solely responsible for any such charges.</p>
<p>8.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Paid Services and / or Fees</p>
<p>If you purchase any services that we offer for a fee (&ldquo;Paid Services&rdquo;), you agree to pay the applicable fees for the Paid Services when due plus all related taxes. All applicable taxes are calculated based on the billing information you provide us at the time of purchase. You agree to reimburse us for all collection costs and interest for any overdue amounts. Unless otherwise denoted, all fees are assessed in U.S. dollars. You also agree that Aday and its third-party service providers providing payment processing services may store your payment information. We may charge your payment information for subsequent charges you authorize, such as account upgrades or other special charges authorized by you. If the payment method you use with us reaches its expiration date and you do not edit the applicable information or cancel such Paid Service, you authorize us to continue billing that payment method and you remain responsible for any uncollected amounts.</p>
<p>If you purchase a subscription to a Paid Service, you will be billed for your first month immediately upon purchasing or upgrading to a subscription account. Unless otherwise set forth on an applicable ordering document incorporating these Terms, the Services are billed in advance on a monthly basis and are non-refundable. For any upgrade or downgrade in plan level, your payment information will automatically be charged the new rate on your next billing cycle in addition to the prorated change in the amount of your subscription for the remainder of the current billing cycle (downgrading your plan level may cause the loss of features or capacity of your account; Aday does not accept any liability for such loss). Your subscription account shall automatically renew, provided that you may cancel the subscription any time before the end of the current billing period and the cancellation will take effect on the next billing period. You shall retain access to such Paid Services from the time you cancel until the start of the next billing period, but you will not receive a refund or credit for any days remaining in your current billing period.</p>
<p>In connection with Paid Services, Aday, in our sole discretion, may give away credits for promotional purposes or any other reason. Credits, including promotional credits, may have expiration dates connected to them. Credits will no longer be valid following their respective expiration dates, if applicable.</p>
<p>Aday may offer certain customers free trials to Paid Services. If you purchase a subscription to a Paid Service that includes a free trial, you will receive free access to such Paid Service for the duration of the free trial period. At the end of the applicable free trial period, you will be charged the price of the subscription for such Paid Service and may continue to be charged until you cancel your subscription. To avoid charges, you must cancel before the end of the free trial period. Failure to pay may result in the termination of your subscription.</p>
<p>You may cancel or suspend your Paid Services by cancelling your account using the&nbsp;My Account page provided through the Service. Unless expressly stated to the contrary, we do not guarantee refunds for lack of usage, dissatisfaction or any other reason. Paid Services may be subject to additional terms, in addition to these Terms, related to the provision of the Paid Service.</p>
<p>9.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Proprietary Rights and Property of Aday Technologies</p>
<p>A.&nbsp;&nbsp;&nbsp;&nbsp;Aday Content</p>
<p>Except for your User Content, the Service and all materials therein or transferred thereby, including, without limitation, software, images, text, graphics, illustrations, logos, patents, trademarks, service marks, copyrights, photographs, audio, videos, music, and User Content belonging to other Users (the &ldquo;Aday Content&rdquo;), and all Intellectual Property Rights related thereto, are the exclusive property of Aday and its licensors (including other Users who post User Content to the Service). Except as explicitly provided herein, nothing in these Terms shall be deemed to create a license in or under any such Intellectual Property Rights, and you agree not to sell, license, rent, modify, distribute, copy, reproduce, transmit, publicly display, publicly perform, publish, adapt, edit or create derivative works from any Aday Content. Use of the Aday Content for any purpose not expressly permitted by these Terms is prohibited.</p>
<p>B.&nbsp;&nbsp;&nbsp;&nbsp;Aday Data</p>
<p>The Service contains data, information, and other content not owned by you, such as ratings, status, and other indicators, as well as usage and other metrics (&ldquo;Aday Data&rdquo;). You understand and agree that regardless of terminology used, Aday Data represents a limited license right governed solely by the terms of these Terms and available for distribution at Aday&rsquo;s sole discretion. Aday Data is not redeemable for any sum of money or monetary value from Aday at any time. You acknowledge that you do not own the account you use to access the Service, nor do you possess any rights of access or rights to data stored by or on behalf of Aday on our servers, including without limitation any data representing or embodying any or all of your Aday Data. You agree that Aday has the absolute right to manage, regulate, control, modify and/or eliminate Aday Data as it sees fit in its sole discretion, in any general or specific case, and that Aday will have no liability to you based on its exercise of such right. All data on Aday&rsquo;s servers are subject to deletion, alteration or transfer.</p>
<p>NOTWITHSTANDING ANY VALUE ATTRIBUTED TO SUCH DATA BY YOU OR ANY THIRD PARTY, YOU UNDERSTAND AND AGREE THAT ANY DATA, ACCOUNT HISTORY AND ACCOUNT CONTENT RESIDING ON OUR SERVERS, MAY BE DELETED, ALTERED, MOVED OR TRANSFERRED AT ANY TIME FOR ANY REASON IN OUR SOLE DISCRETION, WITH OR WITHOUT NOTICE AND WITH NO LIABILITY OF ANY KIND. ADAY DOES NOT PROVIDE OR GUARANTEE, AND EXPRESSLY DISCLAIMS, ANY VALUE, CASH OR OTHERWISE, ATTRIBUTED TO ANY DATA RESIDING ON OUR SERVERS.</p>
<p>C.&nbsp;&nbsp;&nbsp;&nbsp;Feedback</p>
<p>You may choose to, or we may invite you to, submit comments or ideas about the Service, including without limitation about how to improve the Service or our products (&ldquo;Feedback&rdquo;). By submitting any Feedback, you agree that your disclosure is gratuitous, unsolicited and without restriction and will not place Aday under any fiduciary or other obligation, and that we are free to use and / or implement the Feedback without any additional compensation to you, and/or to disclose the Feedback on a non-confidential basis or otherwise to anyone. You further acknowledge that, by acceptance of your submission, Aday does not waive any rights to use similar or related ideas previously known to Aday, or developed by its employees, or obtained from sources other than you.</p>
<p>10.&nbsp;&nbsp;No Professional Advice</p>
<p>If we provide professional information (for example, medical, legal, or financial information), such information is for informational purposes only and should not be construed as professional advice. No action should be taken based upon any professional information contained in or provided by us. You should seek independent professional advice from a person who is licensed and/or qualified in the applicable area.</p>
<p>11.&nbsp;&nbsp;Copyright Protected Materials</p>
<p>Since we respect artist and content owner rights, it is Company&rsquo;s policy to respond to alleged infringement notices that comply with the Digital Millennium Copyright Act of 1998 (&ldquo;DMCA&rdquo;).</p>
<p>If you believe that your copyrighted work has been copied in a way that constitutes copyright infringement and such unauthorized copy is accessible through the Service, please notify Aday&rsquo;s copyright agent as set forth in the DMCA. For your complaint to be valid under the DMCA, you must provide the following information in writing:</p>
<ol>
<li>An electronic or physical signature of a person authorized to act on behalf of the copyright owner;</li>
<li>Identification of the copyrighted work that you claim has been infringed;</li>
<li>Identification of the material that is claimed to be infringing and where it is located on the Service;</li>
<li>Information reasonably sufficient to permit Company to contact you, such as your address, telephone number, and, e-mail address;</li>
<li>A statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or law; and</li>
<li>A statement, made under penalty of perjury, that the above information is accurate, and that you are the copyright owner or are authorized to act on behalf of the owner.</li>
</ol>
<p>The above information must be submitted to the following DMCA Agent:</p>
<p>Address:&nbsp;&nbsp;&nbsp;&nbsp;Aday Technologies, Inc.</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;125 Western Avenue</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Boston, MA 02163</p>
<p>Telephone: (857) 250-0995</p>
<p>Email: tos@adayjobs.com</p>
<p>UNDER FEDERAL LAW, IF YOU KNOWINGLY MISREPRESENT THAT ONLINE MATERIAL IS INFRINGING ON INTELLECTUAL PROPERTY RIGHTS, YOU MAY BE SUBJECT TO CRIMINAL PROSECUTION FOR PERJURY AND CIVIL PENALTIES, INCLUDING MONETARY DAMAGES, COURT COSTS, AND ATTORNEYS&rsquo; FEES.</p>
<p>Please note that this procedure is exclusively for notifying Company and its affiliates that your copyrighted material has been infringed. The preceding requirements are intended to comply with Company&rsquo;s rights and obligations under the DMCA, including 17 U.S.C. &sect;512(c), but do not constitute legal advice. It may be advisable to contact an attorney regarding your rights and obligations under the DMCA and other applicable laws.</p>
<p>In accordance with the DMCA and other applicable law, Company has adopted a policy of terminating, in appropriate circumstances, Users who are deemed in Company&rsquo;s sole discretion to be repeat infringers. Company may also at its sole discretion limit access to the Service and/or terminate the accounts of any Users who infringe any Intellectual Property Rights of others, whether or not there is any repeat infringement.</p>
<p>12.&nbsp;&nbsp;Export Control Laws</p>
<p>The Services may be subject to export control restrictions of the United States, the European Union, Canada or other jurisdictions. By using the Services, you represent and warrant that (i) you are not located in any country, or exporting the Service to any person or place, to which the United States, the European Union, or any other jurisdiction has embargoed goods or that has been designated by the U.S. Government as a &ldquo;terrorist supporting&rdquo; country; and (ii) you are not listed on any U.S. Government list of prohibited or restricted parties. You agree to abide by U.S. and other applicable export control laws and not to transfer, by electronic transmission or otherwise, any content subject to restrictions under such laws to a national destination prohibited by such laws, without first obtaining, and then complying with, any requisite government authorization. You further agree not to upload to Services any Content, data or software that cannot be exported without prior written government authorization, including, but not limited to, certain types of encryption software. The assurances and commitments in this Section shall survive termination of these Terms.</p>
<p>13.&nbsp;&nbsp;Right to Restrict or Terminate Access</p>
<p>Aday may deny or restrict your access to all or part of the Site or Services without notice in its reasonable discretion if it deems that you have engaged in any conduct or activities that Aday, in its reasonable discretion, believes violates the letter or spirit of any of these Terms. If Aday denies or restricts your access to the Services because of such a violation, you shall have no right to obtain any refund or credit for the subscriptions fees you have paid.</p>
<p>14.&nbsp;&nbsp;Privacy</p>
<p>We care about the privacy of our Users. You understand that by using the Services you consent to the collection, use, and disclosure of your personally identifiable information and aggregate data as set forth in our Privacy Policy, and you agree to have your personally identifiable information collected, used, transferred to, and processed in the United States.</p>
<p>15.&nbsp;&nbsp;Security</p>
<p>Aday Technologies is committed to protecting the security of your personal information. We use a variety of commercially reasonable security technologies and procedures to help protect your personal information from unauthorized access, use or disclosure. We cannot, however, guarantee that unauthorized third parties will never be able to defeat or circumvent our security measures or use your personal information for improper purposes. You acknowledge that you provide your personal information at your own risk.</p>
<p>You shall use your best efforts to prevent unauthorized use of our Services, your account, or User Content, and shall promptly report to Aday any suspected unauthorized use or other breach of security. We encourage you to use &ldquo;strong&rdquo; passwords (passwords that use a combination of upper and lower case letters, numbers and symbols) with your account. You shall be solely responsible for any unauthorized use of your account, identification numbers or passwords until we receive written notice of a breach of security and a request to block further access for such numbers and passwords.</p>
<p>16.&nbsp;&nbsp;Vendors and Contractors</p>
<p>Aday may use vendors, contractors or other third-party service provides to help provide the Service to you, and we may change our use of such vendors and contractors at our sole discretion and without notice to you.</p>
<p>17.&nbsp;&nbsp;Third Party Sites</p>
<p>Our Site or Services may contain links to and from third party websites of business partners, advertisers, social media sites, professional and government organizations, publications, and our users may post links to third party websites. Aday does not endorse or assume any responsibility for any such third-party sites, information, materials, products, or services. If you access a third-party website or service from the Service or share your User Content on or through any third-party website or service, you do so at your own risk, and you understand that these Terms and Aday&rsquo;s Privacy Policy do not apply to your use of such sites. You expressly relieve Aday from any and all liability arising from your use of any third-party website, service, or Content, including without limitation User Content submitted by other Users. Additionally, your dealings with or participation in promotions of advertisers found on the Service, including payment and delivery of goods, and any other terms (such as warranties) are solely between you and such advertisers. You agree that Aday shall not be responsible for any loss or damage of any sort relating to your dealings with such advertisers.</p>
<p>18.&nbsp;&nbsp;Children and Minors</p>
<p>Our Site and Services are not intended for anyone under the age of 13. We do not knowingly collect personal information from children under 13. By using our Site or Services you affirm that you are at least 13 years of age. Any use or access to the Service by anyone under 13 is strictly prohibited and in violation of these Terms.</p>
<p>Any use of or access to the Service by anyone under 18 is only permitted with the express written permission of such individual&rsquo;s legal guardian, and, if necessary, you represent and warrant that you have received such permission. The Service is not designed for use by or in connection with anyone under the age of 18, and you accept all responsibility that may arise from your use of the Service in connection with any minors.</p>
<p>19.&nbsp;&nbsp;Disclaimer of Warranty</p>
<p>Actual service coverage, speeds, locations and quality may vary. Aday will attempt to provide the Services at all times, except for limited periods for maintenance and repair. However, the Services and Site may be subject to unavailability for a variety of factors beyond our control including emergencies, third-party service failures, transmission, equipment or network problems or limitations, interference, signal strength, and may be interrupted, limited or curtailed. Delays or omissions may occur. We are not responsible for data, messages or pages lost, not delivered, delayed or misdirected because of interruptions or performance issues with the Site, Services, or communications services or networks. We may impose usage or Services limits, suspend the Services, or block certain kinds of usage in our sole discretion to protect users, the Services or the Site. The accuracy and timeliness of data received is not guaranteed.</p>
<p>THE SERVICES ARE PROVIDED ON AN &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; BASIS. USE OF THE SERVICE IS AT YOUR OWN RISK. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICES ARE PROVIDED WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM COMPANY OR THROUGH THE SERVICE WILL CREATE ANY WARRANTY NOT EXPRESSLY STATED HEREIN. WITHOUT LIMITING THE FOREGOING, COMPANY, ITS SUBSIDIARIES, ITS AFFILIATES, AND ITS LICENSORS DO NOT WARRANT THAT THE CONTENT IS ACCURATE, RELIABLE OR CORRECT; THAT THE SERVICES WILL MEET YOUR REQUIREMENTS; THAT THE SERVICES WILL BE AVAILABLE AT ANY PARTICULAR TIME OR LOCATION, UNINTERRUPTED OR SECURE; THAT ANY DEFECTS OR ERRORS WILL BE CORRECTED; OR THAT THE SERVICES ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. ANY CONTENT DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE ELECTRONIC AMENITIES IS DOWNLOADED AT YOUR OWN RISK AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR MOBILE DEVICE OR LOSS OF DATA THAT RESULTS FROM SUCH DOWNLOAD OR YOUR USE OF THE ELECTRONIC AMENITIES.</p>
<p>COMPANY DOES NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE ELECTRONIC AMENITIESOR ANY HYPERLINKED WEBSITE OR SERVICE, AND COMPANY WILL NOT BE A PARTY TO OR IN ANY WAY MONITOR ANY TRANSACTION BETWEEN YOU AND THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES.</p>
<p>FEDERAL LAW AND SOME STATES, PROVINCES AND OTHER JURISDICTIONS DO NOT ALLOW THE EXCLUSION AND LIMITATIONS OF CERTAIN IMPLIED WARRANTIES, SO THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU. THIS AGREEMENT GIVES YOU SPECIFIC LEGAL RIGHTS, AND YOU MAY ALSO HAVE OTHER RIGHTS WHICH VARY FROM STATE TO STATE. THE DISCLAIMERS AND EXCLUSIONS UNDER THIS AGREEMENT WILL NOT APPLY TO THE EXTENT PROHIBITED BY APPLICABLE LAW.</p>
<p>20.&nbsp;&nbsp;Limitation of Liability</p>
<p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL COMPANY, ITS AFFILIATES, AGENTS, DIRECTORS, EMPLOYEES, SUPPLIERS, OR LICENSORS BE LIABLE FOR ANY INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES, INCLUDING WITHOUT LIMITATION DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA, OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR RELATING TO THE USE OF, OR INABILITY TO USE, THE ELECTRONIC AMENITIES OR THE SERVICES. UNDER NO CIRCUMSTANCES WILL COMPANY BE RESPONSIBLE FOR ANY DAMAGE, LOSS, OR INJURY RESULTING FROM HACKING, TAMPERING, OR OTHER UNAUTHORIZED ACCESS OR USE OF THE SERVICES OR OF YOUR ACCOUNT OR OF THE INFORMATION CONTAINED THEREIN.</p>
<p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, COMPANY ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT; (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO OR USE OF OUR SERVICES; (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION STORED THEREIN; (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE ELECTRONIC AMENITIES; (V) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE THAT MAY BE TRANSMITTED TO OR THROUGH OUR ELECTRONIC AMENITIES BY ANY THIRD PARTY; (VI) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE THROUGH THE ELECTRONIC AMENITIES; AND/OR (VII) USER CONTENT OR THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY. IN NO EVENT SHALL COMPANY, ITS AFFILIATES, AGENTS, DIRECTORS, EMPLOYEES, SUPPLIERS, OR LICENSORS BE LIABLE TO YOU FOR ANY CLAIMS, PROCEEDINGS, LIABILITIES, OBLIGATIONS, DAMAGES, LOSSES, OR COSTS IN AN AMOUNT EXCEEDING THE AMOUNT YOU PAID TO COMPANY HEREUNDER OR $100.00, WHICHEVER IS GREATER.</p>
<p>THIS LIMITATION OF LIABILITY SECTION APPLIES WHETHER THE ALLEGED LIABILITY IS BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR ANY OTHER BASIS, EVEN IF COMPANY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION.</p>
<p>SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATIONS OR EXCLUSIONS MAY NOT APPLY TO YOU. THIS AGREEMENT GIVES YOU SPECIFIC LEGAL RIGHTS, AND YOU MAY ALSO HAVE OTHER RIGHTS WHICH VARY FROM STATE TO STATE. THE DISCLAIMERS, EXCLUSIONS, AND LIMITATIONS OF LIABILITY UNDER THIS AGREEMENT WILL NOT APPLY TO THE EXTENT PROHIBITED BY APPLICABLE LAW.</p>
<p>The Electronic Amenities and Services are controlled and operated from facilities in the United States. Company makes no representations that the Electronic Amenities and Services are appropriate or available for use in other locations. Those who access or use the Services from other jurisdictions do so at their own volition and are entirely responsible for compliance with all applicable United States and local laws and regulations, including but not limited to export and import regulations. You may not use the Services if you are a resident of a country embargoed by the United States, or are a foreign person or entity blocked or denied by the United States government. Unless otherwise explicitly stated, all materials found on or through the Services are solely directed to individuals, companies, or other entities lawfully located in the United States.</p>
<p>21.&nbsp;&nbsp;Indemnification</p>
<p>You agree to defend, indemnify and hold Aday, its subsidiaries, agents, licensors, managers, and other affiliated companies, and their employees, contractors, agents, officers, and directors, harmless from any claim or demand, including reasonable attorneys&rsquo; fees, made by any third party arising out of or relating to (i) your use of and access to the Services, including any data or Content transmitted or received by you; (ii) your violation of any term of these Terms, including without limitation your breach of any of the representations and warranties above; (iii) your violation of any third-party right, including without limitation any right of privacy or Intellectual Property Rights; (iv) your violation of any applicable local, state, or federal law, rule, or regulation; (v) User Content or any content that is submitted via your account including without limitation misleading, false, or inaccurate information; (vi) your willful misconduct; or (vii) any other party&rsquo;s access and use of the Services using your unique username, password, or other appropriate security code. Aday reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to defense by you.</p>
<p>22.&nbsp;&nbsp;Governing Law, Arbitration, Waiver of Class Action And Jury Trial</p>
<p>A.&nbsp;&nbsp;&nbsp;&nbsp;Governing Law, Jurisdiction, and Venue</p>
<p>These Terms shall be governed by, and construed in accordance with, the laws of the state of Massachusetts, without reference to its choice of law rules. Subject to the arbitration provisions below, exclusive venue for any action arising out of or in connection with this agreement shall be in Boston, Massachusetts. The parties each hereby consent to the jurisdiction and venue in Boston, Massachusetts and waive any objections to such jurisdiction and venue. Notwithstanding the foregoing, you agree that Aday Technologies shall be entitled to bring any suit, action or proceeding against you, whether damages sought are injunctive or otherwise, for breach of these Terms in any relevant jurisdiction. You waive any and all objections to the exercise of jurisdiction over you by such courts and to venue in such courts.</p>
<p>B.&nbsp;&nbsp;&nbsp;&nbsp;Dispute Resolution and Arbitration.</p>
<p>READ THIS SECTION CAREFULLY BECAUSE IT REQUIRES THE PARTIES TO ARBITRATE THEIR DISPUTES AND LIMITS THE MANNER IN WHICH YOU MAY SEEK RELIEF FROM COMPANY. For any dispute with Company, you agree to first contact us at tos@adayjobs.com and attempt to resolve the dispute with us informally. In the unlikely event that Aday has not been able to resolve a dispute it has with you after sixty (60) days (&ldquo;Informal Dispute Resolution Process&rdquo;), you and Aday each agree to resolve any claim, dispute, or controversy (excluding any claims for injunctive or other equitable relief as provided below) arising out of or in connection with or relating to these Terms, or the breach or alleged breach thereof (collectively, &ldquo;Claims&rdquo;), by binding arbitration by the alternative dispute resolution business JAMS, under the Optional Expedited Arbitration Procedures then in effect for JAMS and available at the JAMS website, except as provided herein. JAMS may be contacted at www.jamsadr.com. The arbitration will be conducted in Middlesex County, Massachusetts, unless you and the Company agree otherwise. If you are using the Service for commercial purposes, each party will be responsible for paying any JAMS filing, administrative, and arbitrator fees in accordance with JAMS rules, and the award rendered by the arbitrator shall include costs of arbitration, reasonable attorneys&rsquo; fees, and reasonable costs for expert and other witnesses. If you are an individual using the Services for non-commercial purposes: (i) JAMS may require you to pay a fee for the initiation of your case, unless you apply for and successfully obtain a fee waiver from JAMS; (ii) the award rendered by the arbitrator may include your costs of arbitration, your reasonable attorney&rsquo;s fees, and your reasonable costs for expert and other witnesses; and (iii) you may sue in a small claims court of competent jurisdiction without first engaging in arbitration, but this does not absolve you of your commitment to engage in the Informal Dispute Resolution Process. Any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction. Nothing in this Section shall be deemed as preventing Company from seeking injunctive or other equitable relief from the courts as necessary to prevent the actual or threatened infringement, misappropriation, or violation of our data security, Intellectual Property Rights, or other proprietary rights.</p>
<p>C.&nbsp;&nbsp;&nbsp;&nbsp;Class Action / Jury Trial Waiver</p>
<p>WITH RESPECT TO ALL PERSONS AND ENTITIES, REGARDLESS OF WHETHER THEY HAVE OBTAINED OR USED THE SERVICE FOR PERSONAL, COMMERCIAL, OR OTHER PURPOSES, ALL CLAIMS MUST BE BROUGHT IN THE PARTIES&rsquo; INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS ACTION, COLLECTIVE ACTION, PRIVATE ATTORNEY GENERAL ACTION, OR OTHER REPRESENTATIVE PROCEEDING. THIS WAIVER APPLIES TO CLASS ARBITRATION, AND, UNLESS WE AGREE OTHERWISE, THE ARBITRATOR MAY NOT CONSOLIDATE MORE THAN ONE PERSON&rsquo;S CLAIMS. YOU AGREE THAT, BY ENTERING INTO THIS AGREEMENT, YOU AND COMPANY EACH WAIVE THE RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE IN A CLASS ACTION, COLLECTIVE ACTION, PRIVATE ATTORNEY GENERAL ACTION, OR OTHER REPRESENTATIVE PROCEEDING OF ANY KIND.</p>
<p>D.&nbsp;&nbsp;&nbsp;Limited Time to Bring Claim.</p>
<p>Subject to any applicable law to the contrary, you agree that any cause of action arising out of or related to the use of our Site or Services must be commenced within one (1) year after the cause of action accrues, or such action will be permanently barred.</p>
<p>E.&nbsp;&nbsp;&nbsp;&nbsp;No Injunctive Relief.</p>
<p>In no event shall you seek or be entitled to rescission, injunctive or other equitable relief, or to enjoin or restrain the operation of the Site or Services, or any other materials used, displayed, or connected therewith.</p>
<p>23.&nbsp;&nbsp;General Terms</p>
<p>A.&nbsp;&nbsp;&nbsp;&nbsp;Entire Agreement.</p>
<p>These Terms, along with any rules, guidelines, or policies published on the Aday Site constitute the sole and entire agreement between Aday Technologies, Inc. and you with respect to the use of our Site and Services. The Terms supersede all prior and contemporaneous understandings, agreements, representations and warranties, both written and oral, with respect to the Site and Services. If there is any conflict between the Terms and any other rules or instructions on the Site or Services, the Terms shall control.</p>
<p>B.&nbsp;&nbsp;&nbsp;&nbsp;Amendments.</p>
<p>No amendment to these Terms by you by shall be effective unless acknowledged and agreed to in writing by Aday. Notwithstanding the foregoing, Aday reserves the right, in its sole discretion, to modify these Terms or the policies referenced herein at any time as set forth above.</p>
<p>C.&nbsp;&nbsp;&nbsp;&nbsp;Assignment.</p>
<p>You may not assign your rights or obligations under these Terms without the prior written consent of Aday, which may be withheld in Aday&rsquo;s sole discretion.</p>
<p>D.&nbsp;&nbsp;&nbsp;Severability.</p>
<p>If any provision of these Terms is held by a court or other tribunal of competent jurisdiction to be invalid, illegal or unenforceable for any reason, such provision shall be eliminated or limited to the minimum extent such that the remaining provisions of the Terms will continue in full force and effect.</p>
<p>E.&nbsp;&nbsp;&nbsp;&nbsp;Notice.</p>
<p>If you have any questions, complaints, or claims, you should contact Aday Technologies, Inc. using the Contact Us page available through the Site and Services.</p>
<p>All notices of copyright infringement claims should be sent to the below address in the manner and by the means set forth in the Copyright section of the Terms:</p>
<p>Aday Technologies, Inc.</p>
<p>125 Western Avenue</p>
<p>Boston, MA 02163</p>
<p>&nbsp;</p>
<p>F.&nbsp;&nbsp;&nbsp;&nbsp;No Waiver.</p>
<p>No waiver of any term of these Terms shall be deemed a further or continuing waiver of such term or any other term, and any failure by Aday to assert any right or provision under the Terms shall not constitute a waiver of such right or provision.</p>
<p>G.&nbsp;&nbsp;&nbsp;Survival.</p>
<p>Any sections or terms which by their nature should survive or are otherwise necessary to enforce the purpose of these Terms, will survive the termination of these Terms and termination of the Site or Services.</p>
<p>H.&nbsp;&nbsp;&nbsp;Headings.</p>
<p>All headings included in these Terms are included for convenience only, and shall not be considered in interpreting these Terms.</p>
<p>I.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Third-Party Beneficiaries.</p>
<p>If you are accessing the Services through Mobile Software from the Apple App Store or Google Play Store, Aday and you acknowledge and agree that the relevant application store provider, whether Apple or Google (&ldquo;Application Store Providers&rdquo;), and their respective subsidiaries, are third party beneficiaries of these Terms, and that, upon your acceptance of the terms and conditions of these Terms, the Application Store Providers have the right (and will be deemed to have accepted the right) to enforce these Terms against you as a third party beneficiary thereof. Except for the foregoing or as otherwise expressly set forth herein, there shall exist no right of any person, other than you and Aday, to claim a beneficial interest in these Terms or any rights occurring by virtue of these Terms.</p>
<p>J.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cumulative Rights of Aday Technologies, Inc.</p>
<p>These Terms do not limit any rights that Aday may have pursuant to any laws. All rights and remedies available to Aday, pursuant to these Terms or otherwise, at law or in equity, are cumulative and not exclusive of any other rights or remedies that may be available to Aday.</p>
<p>K.&nbsp;&nbsp;&nbsp;&nbsp;Contact.</p>
<p>If you have a questions or regarding Aday Technologies or the Terms, please contact us using the Contact Us page available through the Site and Services.</p>
<p>&nbsp;</p>
<p><strong><em>Effective Date: April 22, 2017</em></strong></p>
<p>&nbsp;</p>
`;

/**
 * @description TermsOfService for Aday Technologies, updated April 21, 2017
 * @type {[type]}
 */
export default class TermsOfService extends React.Component {
    render() {
        return (
            <ScrollView style = {
                 styles.container
            }>
                <Image style={styles.logoImage} source={require('../components/assets/logos/aday-logo-bw.png')}/>
                <View style={{ marginRight: 15, marginLeft: 15}}>
                    <HTMLView value={htmlContent} renderNode={renderNode} />
                </View>
            </ScrollView>
        );
    }
}

const styles = StyleSheet.create({
    a: {
        fontWeight: '300',
        color: '#FF3366',
    },
    container: {
        flex: 1,
        backgroundColor: '#F7F7F7',
    },
    logoImage: {
        width: 110,
        resizeMode: 'contain',
        alignSelf: 'center'
    },
});
